### ISSUE TITLE
Update to the new formatter API

### ISSUE THREAD

**Issue by rosskevin** [alienfast/cucumber_statistics#11]
@callahat discovered a new api for timing:

> Turns out there is a new formatter api that should be used instead.
> 
> ( Cuke group thread on google groups: https://groups.google.com/forum/#!topic/cukes/HIGakoahWEA )

Help wanted, please PR - this is a good/easy first enhancement (it appears).

**Comment by rosskevin** [comment]
This now appears to be a bug - broken in cucumber > 3

```
undefined method `regexp_source' for #<Cucumber::Glue::StepDefinition:0x00007ffdfdc01428> (NoMethodError)
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber_statistics-2.3.0/lib/cucumber_statistics/formatter.rb:29:in `after_step_result'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-3.1.1/lib/cucumber/formatter/ignore_missing_messages.rb:11:in `method_missing'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/ast.rb:117:in `accept'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:580:in `step_invocation'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:543:in `step_invocation'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:387:in `print_step'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:251:in `after_test_step'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:107:in `after_test_step'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:31:in `block in initialize'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:34:in `block in broadcast'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:34:in `each'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:34:in `broadcast'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:40:in `method_missing'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:35:in `around_hook'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-core-3.1.0/lib/cucumber/core/test/around_hook.rb:12:in `describe_to'
/Users/kross/.rvm/gems/ruby-2.5.1@archetype/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:120:in `block (2 levels) in compose_around_hooks'
```

**Comment by rosskevin** [comment]
Partial fix (not a new formatter api usage): https://github.com/alienfast/cucumber_statistics/pull/15

**Comment by rosskevin** [comment]
#15 and 3.0.0 gets us by for now, so updating to the new formatter is a nice to have enhancement.
